export const TRACK_PRODUCT_CLICK_REQUEST = "TRACK_PRODUCT_CLICK_REQUEST";
export const TRACK_PRODUCT_CLICK_SUCCESS = "TRACK_PRODUCT_CLICK_SUCCESS";
export const TRACK_PRODUCT_CLICK_FAIL = "TRACK_PRODUCT_CLICK_FAIL";
