export const NEW_SELL_PRODUCT_REQUEST = "NEW_SELL_PRODUCT_REQUEST"; 
export const NEW_SELL_PRODUCT_SUCCESS = "NEW_SELL_PRODUCT_SUCCESS"; 
export const NEW_SELL_PRODUCT_RESET = "NEW_SELL_PRODUCT_RESET"; 
export const NEW_SELL_PRODUCT_FAIL = "NEW_SELL_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";